name: flutter_app
description: "An app to find cheapest gas prices"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_map: ^8.2.2
  location: ^8.0.1
  latlong2: ^0.9.1
  http: ^1.5.0
  geolocator: ^14.0.2
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
